module.exports = [
  {code: "IDENT", doc: "CARTA DI IDENTITA'"}, 
  {code: "CIDIP", doc: "CARTA ID. DIPLOMATICA"}, 
  {code: "IDELE", doc: "CARTA IDENTITA' ELETTRONICA"}, 
  {code: "CERID", doc: "CERTIFICATO D'IDENTITA'"}, 
  {code: "PASSE", doc: "PASSAPORTO DI SERVIZIO"}, 
  {code: "PASDI", doc: "PASSAPORTO DIPLOMATICO"}, 
  {code: "PASOR", doc: "PASSAPORTO ORDINARIO"}, 
  {code: "PATEN", doc: "PATENTE DI GUIDA"}, 
  {code: "PATNA", doc: "PATENTE NAUTICA"}, 
  {code: "PORM5", doc: "PORTO D'ARMI GUARDIE GIUR"}, 
  {code: "PORM3", doc: "PORTO D'ARMI USO SPORTIVO"}, 
  {code: "PORM2", doc: "PORTO FUCILE DIF. PERSON."}, 
  {code: "PORM1", doc: "PORTO FUCILE USO CACCIA"}, 
  {code: "PORM4", doc: "PORTO PISTOLA DIF. PERSON"}, 
  {code: "TENAV", doc: "TES. ENTE NAZ. ASSIS.VOLO"}, 
  {code: "TFEXD", doc: "TES. FERROV. EX DEPUTATI"}, 
  {code: "TFERD", doc: "TES. FERROVIARIA DEPUTATI"}, 
  {code: "TESPT", doc: "TES. POSTE E TELECOMUNIC."}, 
  {code: "TECAM", doc: "TES. UNICO PER LA CAMERA"}, 
  {code: "TEDOG", doc: "TES.DOGANALE RIL.MIN.FIN."}, 
  {code: "CFMIL", doc: "TESS. AG. E AG.SC. C.F.S."}, 
  {code: "PPAGE", doc: "TESS. AGENTI/ASS.TI P.P."}, 
  {code: "PSAPP", doc: "TESS. AGENTI/ASS.TI P.S."}, 
  {code: "ACMIL", doc: "TESS. APP.TO AG.CUSTODIA"}, 
  {code: "CCMIL", doc: "TESS. APP.TO CARABINIERI"}, 
  {code: "GFMIL", doc: "TESS. APP.TO FINANZIERE"}, 
  {code: "VIMIL", doc: "TESS. APP.TO/VIG. URBANO"}, 
  {code: "VVMIL", doc: "TESS. APP.TO/VIG. VV.FF."}, 
  {code: "TESCS", doc: "TESS. CONSIGLIO DI STATO"}, 
  {code: "TESCA", doc: "TESS. CORTE D'APPELLO"}, 
  {code: "TECOC", doc: "TESS. CORTE DEI CONTI"}, 
  {code: "TEFSE", doc: "TESS. FERROV. SENATO"}, 
  {code: "PSFUN", doc: "TESS. FUNZIONARI P.S."}, 
  {code: "TETEL", doc: "TESS. IDENTIF.TELECOM IT."}, 
  {code: "TEAMC", doc: "TESS. ISCR. ALBO MED/CHI."}, 
  {code: "TEAOD", doc: "TESS. ISCRIZ. ALBO ODONT."}, 
  {code: "PPISP", doc: "TESS. ISPETTORI P.P."}, 
  {code: "PSISP", doc: "TESS. ISPETTORI P.S."}, 
  {code: "TESEA", doc: "TESS. MEMBRO EQUIP. AEREO"}, 
  {code: "MMMIL", doc: "TESS. MILIT. M.M."}, 
  {code: "SDMIL", doc: "TESS. MILIT. TRUPPA SISMI"}, 
  {code: "EIMIL", doc: "TESS. MILITARE E.I."}, 
  {code: "TENAT", doc: "TESS. MILITARE NATO"}, 
  {code: "AMMIL", doc: "TESS. MILITARE TRUPPA A.M"}, 
  {code: "TESAE", doc: "TESS. MIN. AFFARI ESTERI"}, 
  {code: "TESMB", doc: "TESS. MIN.BEN.E ATT.CULT."}, 
  {code: "TEMPI", doc: "TESS. MIN.PUBB.ISTRUZIONE"}, 
  {code: "TESMN", doc: "TESS. MINIST. TRASP/NAVIG"}, 
  {code: "TESMD", doc: "TESS. MINISTERO DIFESA"}, 
  {code: "TESMF", doc: "TESS. MINISTERO FINANZE"}, 
  {code: "TESMG", doc: "TESS. MINISTERO GIUSTIZIA"}, 
  {code: "TESMI", doc: "TESS. MINISTERO INTERNO"}, 
  {code: "TESLP", doc: "TESS. MINISTERO LAVORI PU"}, 
  {code: "TESMS", doc: "TESS. MINISTERO SANITA'"}, 
  {code: "TESMT", doc: "TESS. MINISTERO TESORO"}, 
  {code: "TESOG", doc: "TESS. ORDINE GIORNALISTI"}, 
  {code: "PARLA", doc: "TESS. PARLAMENTARI"}, 
  {code: "MAGIS", doc: "TESS. PERS. MAGISTRATI"}, 
  {code: "GFTRI", doc: "TESS. POL. TRIB. G.D.F."}, 
  {code: "PSFEM", doc: "TESS. POLIZIA FEMMINILE"}, 
  {code: "TESPC", doc: "TESS. PRES.ZA CONS. MIN."}, 
  {code: "TESPI", doc: "TESS. PUBBLICA ISTRUZIONE"}, 
  {code: "DESIS", doc: "TESS. S.I.S.D.E."}, 
  {code: "ACSOT", doc: "TESS. SOTT.LI AG.CUSTODIA"}, 
  {code: "GFSOT", doc: "TESS. SOTT.LI G.D.F."}, 
  {code: "VISOT", doc: "TESS. SOTT.LI VIG. URBANI"}, 
  {code: "VVSOT", doc: "TESS. SOTTUFF.LI VV.FF."}, 
  {code: "AMSOT", doc: "TESS. SOTTUFFICIALI A.M."}, 
  {code: "CCSOT", doc: "TESS. SOTTUFFICIALI CC"}, 
  {code: "EISOT", doc: "TESS. SOTTUFFICIALI E.I."}, 
  {code: "SDSOT", doc: "TESS. SOTTUFFICIALI SISMI"}, 
  {code: "CFSOT", doc: "TESS. SOTTUFICIALI C.F.S."}, 
  {code: "MMSOT", doc: "TESS. SOTTUFICIALI M.M."}, 
  {code: "PPSOV", doc: "TESS. SOVRINTENDENTI P.P."}, 
  {code: "PSSOT", doc: "TESS. SOVRINTENDENTI P.S."}, 
  {code: "ACUFF", doc: "TESS. UFF.LI AG.CUSTODIA"}, 
  {code: "VIUFF", doc: "TESS. UFF.LI VIG.URBANI"}, 
  {code: "CCUFF", doc: "TESS. UFFICIALE"}, 
  {code: "AMUFF", doc: "TESS. UFFICIALI A.M."}, 
  {code: "CFUFF", doc: "TESS. UFFICIALI C.F.S."}, 
  {code: "EIUFF", doc: "TESS. UFFICIALI E.I."}, 
  {code: "GFUFF", doc: "TESS. UFFICIALI G.D.F."}, 
  {code: "MMUFF", doc: "TESS. UFFICIALI M.M."}, 
  {code: "PPUFF", doc: "TESS. UFFICIALI P.P."}, 
  {code: "PSUFF", doc: "TESS. UFFICIALI P.S."}, 
  {code: "SDUFF", doc: "TESS. UFFICIALI SISMI"}, 
  {code: "VVUFF", doc: "TESS. UFFICIALI VV.FF."}, 
  {code: "TESIN", doc: "TESS.ISCR. ALBO INGEGNERI"}, 
  {code: "TESAR", doc: "TESS.ISCR.ALBO ARCHITETTI"}, 
  {code: "TEPOL", doc: "TESS.MIN.POLIT.AGRIC.FOR."}, 
  {code: "TESNO", doc: "TESSERA DELL'ORDINE NOTAI"}, 
  {code: "TESAV", doc: "TESSERA ISCR. ALBO AVVOC."}, 
  {code: "TESDI", doc: "TESSERA RICONOSC. D.I.A."}, 
  {code: "TESUN", doc: "TESSERA U.N.U.C.I."}, 
  {code: "RIFUG", doc: "TITOLO VIAGGIO RIF.POLIT."}
];